import { Montserrat } from "next/font/google";
import "./globals.css";
import SmoothScrollProvider from "./components/SmoothScrollProvider";
import ConsultationSection from "./components/ConsultationSection";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import PageTransition from "./components/PageTransition";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: [
    "100", // Thin
    "200", // Extra Light
    "300", // Light
    "400", // Regular
    "500", // Medium
    "600", // Semi Bold
    "700", // Bold
    "800", // Extra Bold
    "900", // Black
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <PageTransition>
          <SmoothScrollProvider>
            <Navbar />
            {children}
            <ConsultationSection />
            <Footer />
          </SmoothScrollProvider>
        </PageTransition>
      </body>
    </html>
  );
}
